<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loading_indicator</name>
   <tag></tag>
   <elementGuidId>ad17a732-c19c-4db0-9db0-78b08ac2535c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.twikbot-progress-indicator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[1]/div[2]/div</value>
   </webElementProperties>
</WebElementEntity>
