<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_StarsnStripes</name>
   <tag></tag>
   <elementGuidId>fd0dbbaf-8045-4496-b555-218d7da669cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[3]/div[1]/div[2]/div/div[3]/div[9]/img</value>
   </webElementProperties>
</WebElementEntity>
