<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirmation_Accept</name>
   <tag></tag>
   <elementGuidId>eb583e21-4e1e-453c-a16b-736ef7389680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pages-index&quot;]/div[11]/div[2]/div/div[3]/div[1]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[11]/div[2]/div/div[3]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[11]/div[2]/div/div[3]/div[2]/span</value>
   </webElementProperties>
</WebElementEntity>
