<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_PaperPlane</name>
   <tag></tag>
   <elementGuidId>edb711b2-feaa-44cf-ade6-b3f0b022b543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[3]/div[1]/div[2]/div/div[3]/div[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[3]/div[1]/div[2]/div/div[3]/div[4]/img</value>
   </webElementProperties>
</WebElementEntity>
