<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Resize_text_topright</name>
   <tag></tag>
   <elementGuidId>513ec0e0-04bd-4704-9550-068032a57c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pages-index&quot;]/div[1]/div[2]/div[1]/div[3]/div/div/div[1]/div[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div[1]/div[3]/div/div[1]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[1]/div[3]/div/div[1]/div[6]</value>
   </webElementProperties>
</WebElementEntity>
