<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Resize_text_bottomright</name>
   <tag></tag>
   <elementGuidId>c9f8d382-f08f-4639-bff0-00c51ac1d3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pages-index&quot;]/div[1]/div[2]/div[1]/div[3]/div/div/div[1]/div[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div[1]/div[3]/div/div[1]/div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[1]/div[3]/div/div[1]/div[8]</value>
   </webElementProperties>
</WebElementEntity>
