<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Structure</name>
   <tag></tag>
   <elementGuidId>8e09a935-fa3c-47cc-933b-6bb021ad7f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;pages-index&quot;]/div[1]/div[3]/div[2]/div[2]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pages-index&quot;]/div[1]/div[3]/div[2]/div[2]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pages-index&quot;]/div[1]/div[3]/div[2]/div[2]/div/div[2]/span</value>
   </webElementProperties>
</WebElementEntity>
