<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Color</name>
   <tag></tag>
   <elementGuidId>addb1b90-9233-45c2-bd22-2e87cb113f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[3]/div[2]/div[2]/div/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[3]/div[2]/div[2]/div/div[1]/span</value>
   </webElementProperties>
</WebElementEntity>
