<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Font_SerifBold</name>
   <tag></tag>
   <elementGuidId>53cf0f10-484f-4df3-b1ef-4a7613798a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[10]/div[2]/div/div[2]/div/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[10]/div[2]/div/div[2]/div/div[1]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
