<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Loading_indicator</name>
   <tag></tag>
   <elementGuidId>14ee8078-abfc-4d0b-a87f-4da90ef3a5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.twikbot-progress-indicator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[1]/div[2]/div</value>
   </webElementProperties>
</WebElementEntity>
