<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Signature</name>
   <tag></tag>
   <elementGuidId>ee3a799f-0913-44d9-b563-deec8fcdbe3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[3]/div[1]/div[2]/div/div[5]/div[1]/img[2]</value>
   </webElementProperties>
</WebElementEntity>
