<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mode_customisation</name>
   <tag></tag>
   <elementGuidId>2dc64cb5-9e30-48ad-b5c6-7ca18b5cb60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pages-index&quot;]/header/div[2]/div/div[1]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/header/div[2]/div[1]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/header/div[2]/div[1]/div/span</value>
   </webElementProperties>
</WebElementEntity>
