<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mode_customisation_app</name>
   <tag></tag>
   <elementGuidId>33ba2a48-dacb-4984-a7e5-6cc15f64046d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pages-index&quot;]/header/div[2]/div/div[1]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/header/div[2]/div[1]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/header/div[2]/div[1]/div/img</value>
   </webElementProperties>
</WebElementEntity>
